// This file was generated by openscad.generate.py as part of Advent Of Code
// 2021, day 22
union() {
difference() {
union() {
difference() {
union() {
difference() {
union() {
difference() {
union() {
difference() {
union() {
union() {
union() {
union() {
union() {
union() {
union() {
union() {
union() {
translate([-40, -3, -48]) {
cube([48, 53, 55], center=false);
};
translate([-38, -11, -30]) {
cube([49, 49, 50], center=false);
};
};
translate([-43, -16, -38]) {
cube([45, 47, 52], center=false);
};
};
translate([-10, -8, -41]) {
cube([55, 55, 46], center=false);
};
};
translate([-27, -2, -33]) {
cube([47, 48, 46], center=false);
};
};
translate([-41, -18, -34]) {
cube([46, 51, 54], center=false);
};
};
translate([-43, -20, -34]) {
cube([53, 48, 55], center=false);
};
};
translate([-47, -5, -20]) {
cube([46, 55, 53], center=false);
};
};
translate([-20, -40, -16]) {
cube([54, 47, 50], center=false);
};
};
translate([-25, -47, -46]) {
cube([50, 46, 53], center=false);
};
};
translate([-28, -6, 22]) {
cube([20, 11, 16], center=false);
};
};
translate([-34, -16, -43]) {
cube([49, 49, 47], center=false);
};
};
translate([-36, -44, 5]) {
cube([19, 12, 12], center=false);
};
};
translate([-23, -34, -38]) {
cube([46, 46, 51], center=false);
};
};
translate([-24, 26, -18]) {
cube([10, 14, 10], center=false);
};
};
translate([-23, -31, -38]) {
cube([46, 52, 52], center=false);
};
};
translate([-16, 7, -44]) {
cube([11, 13, 15], center=false);
};
};
translate([-8, -18, -27]) {
cube([54, 47, 46], center=false);
};
};
translate([-24, -3, 33]) {
cube([17, 11, 13], center=false);
};
};
translate([-28, -15, -18]) {
cube([47, 55, 54], center=false);
};
};
