name: Update CLOC graph

on:
  workflow_dispatch:
  schedule:
    - cron: "58 4 * 12 *"

jobs:
  graph:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
          with:
            ref: ${{ github.ref }}
            fetch-depth: 0

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Login GitHub Registry
          run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GH_TKN }}

        - name: Run gocloc
          run: docker run --rm -v "${PWD}":/workdir docker.pkg.github.com/hhatto/gocloc/gocloc:latest --by-file --output-type=json --not-match-d="(template|.github|.vscode)" --exclude-ext=txt . > .github/cloc.json

        - name: Install Matplotlib
          run: pip install matplotlib

        - name: Run script  
          run: python .github/clocgen.py .github/cloc.json .github/clocgraph.png

        - name: Git commit and push
          run: |
            git config user.email 'actions@github.com'
            git config user.name 'github-actions'
            git add .github/clocgraph.png .github/cloc.json
            git commit -m 'Update CLOC graph'
            git push origin HEAD:${{ github.ref }}
