name: Update README

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "1 5 * 12 *"

jobs:
  table:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install beautifulsoup4 requests

      - name: Run script  
        run: python .github/tablegen.py .github/README.md ${{ secrets.AOC_SESSION }}

      - name: Prettify markdown
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write .github/README.md
          # dry: True
          commit_message: "Update README"